name: Database Deployment

on:
  push:
    branches:
      - main

jobs:
  db-deploy:
    runs-on: ubuntu-latest

    steps:
    # Step 1: Check out the repository
    - name: Check out the repository
      uses: actions/checkout@v3

    # Step 2: Install Flyway
    - name: Install Flyway
      run: |
        curl -LO https://repo1.maven.org/maven2/org/flywaydb/flyway-commandline/9.15.1/flyway-commandline-9.15.1-linux-x64.tar.gz
        tar -xzf flyway-commandline-9.15.1-linux-x64.tar.gz
        sudo mv flyway-9.15.1 /usr/local/flyway
        export PATH=$PATH:/usr/local/flyway

    # Step 3: Run Flyway migrations
    - name: Run Flyway Migrations
      env:
        FLYWAY_URL: jdbc:sqlserver://${{ secrets.AZURE_SQL_SERVER }};databaseName=${{ secrets.AZURE_SQL_DATABASE }}
        FLYWAY_USER: ${{ secrets.AZURE_SQL_USER }}
        FLYWAY_PASSWORD: ${{ secrets.AZURE_SQL_PASSWORD }}
      run: |
        flyway -url=$FLYWAY_URL \
               -user=$FLYWAY_USER \
               -password=$FLYWAY_PASSWORD \
               -locations=filesystem:./db/upgrades \
               migrate
