name: Azure SQL Database Migration

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  database-migration:
    runs-on: windows-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3

    - name: Run SQL Migration
      run: |
        cd ./Database
        ./databaseUpgrade.Prod.bat
      env:
        SERVER_NAME: ${{ secrets.AZURE_SQL_SERVER }}
        DATABASE_NAME: ${{ secrets.AZURE_SQL_DATABASE }}
        USERNAME: ${{ secrets.AZURE_SQL_USER }}
        PASSWORD: ${{ secrets.AZURE_SQL_PASSWORD }}

    - name: Verify Log File
      run: |
        if (Test-Path ./Database/sql_scripts_log.txt) {
          Write-Host "Log file exists."
        } else {
          Write-Host "Log file not found."
          exit 1
        }
      shell: pwsh

    - name: Print Working Directory
      run: pwd

    - name: List Root Directory
      run: dir /s
      shell: cmd

    - name: List Files for Debugging
      run: dir /s "Database"
      shell: cmd

    - name: Upload Logs
      if: always()
      uses: actions/upload-artifact@v3
      with:
        name: SQLMigrationLogs
        path: ./Database/sql_scripts_log.txt
