name: Azure SQL Database Migration

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  database-migration:
    runs-on: windows-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3

    - name: Run SQL Migration
      run: |
        ./Database/databaseUpgrade.Prod.bat || echo "Batch script failed" >> ./Database/sql_scripts_log.txt
      env:
        SERVER_NAME: ${{ secrets.AZURE_SQL_SERVER }}
        DATABASE_NAME: ${{ secrets.AZURE_SQL_DATABASE }}
        USERNAME: ${{ secrets.AZURE_SQL_USER }}
        PASSWORD: ${{ secrets.AZURE_SQL_PASSWORD }}
      continue-on-error: true

    - name: Verify Log File
      run: |
        if exist ./Database/sql_scripts_log.txt (
          echo Log file exists: ./Database/sql_scripts_log.txt
        ) else (
          echo Log file not found
          exit 1
        )

    - name: Upload Logs
      uses: actions/upload-artifact@v3
      with:
        name: SQLMigrationLogs
        path: |
          ./Database/sql_scripts_log.txt
          ./Database/Upgrade/sql_scripts_log.txt
          ./sql_scripts_log.txt
