name: Azure SQL Database Migration

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  database-migration:
    runs-on: windows-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3

    - name: Setup Environment
      run: |
        echo Setting up environment variables
        set SERVER_NAME=${{ secrets.AZURE_SQL_SERVER }}
        set DATABASE_NAME=${{ secrets.AZURE_SQL_DATABASE }}
        set USERNAME=${{ secrets.AZURE_SQL_USER }}
        set PASSWORD=${{ secrets.AZURE_SQL_PASSWORD }}

    - name: List Files in Database Directory
      run: |
        dir ./Database

    - name: Run SQL Migration
      run: |
        ./Database/databaseUpgrade.Prod.bat
      env:
        SERVER_NAME: ${{ secrets.AZURE_SQL_SERVER }}
        DATABASE_NAME: ${{ secrets.AZURE_SQL_DATABASE }}
        USERNAME: ${{ secrets.AZURE_SQL_USER }}
        PASSWORD: ${{ secrets.AZURE_SQL_PASSWORD }}


    - name: Upload Logs
      uses: actions/upload-artifact@v3
      with:
        name: SQLMigrationLogs
        path: Database/sql_scripts_log.txt
